"""fix reservation relationship

Revision ID: 2dbf660a15bc
Revises: d1aba3846cea
Create Date: 2024-08-02 11:17:12.482352

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2dbf660a15bc"
down_revision = "d1aba3846cea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_reservation",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("reservation_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    with op.batch_alter_table("reservation", schema=None) as batch_op:
        batch_op.drop_constraint("fk_reservation_restaurant_id", type_="foreignkey")
        batch_op.drop_column("restaurant_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reservation", schema=None) as batch_op:
        batch_op.add_column(sa.Column("restaurant_id", sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(
            "fk_reservation_restaurant_id", "restaurant", ["restaurant_id"], ["id"]
        )

    op.drop_table("user_reservation")
    # ### end Alembic commands ###
